version: '3'

services:
  app:
    build: './src/main'
    volumes:
      - './src/main:/usr/src/main'
    environment:
      - 'PORT=80'
    ports:
      - '80:80'

  github-release:
    image: 'github-release'
    build: './src/main'

  docker-push:
    image: 'tmvdl/projects:java'
    build: './src/main'
